# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - gp3-win-scrape

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'gp3-scrape'
  AZURE_FUNCTIONAPP_PACKAGE_NAME: 'ScrapeFunc' # Project path
  BROWSER_PREFETCH_NAME: 'ScrapeFunc.Prefetch' # Browser prefetch project path
  DOTNET_VERSION: '6.0.x' # .NET version

jobs:
  prefetch-build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: 'Resolve Prefetch dependencies'
        shell: bash
        run: |
          pushd './${{ env.BROWSER_PREFETCH_NAME }}'
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet run --no-restore -- ../${{ env.AZURE_FUNCTIONAPP_PACKAGE_NAME }}/output
          popd
          
      - name: 'Resolve Function dependencies'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_NAME }}'
          dotnet build --configuration Release --output ./output
          popd
          
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_NAME }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_SCRAPE_PUBLISH_PROFILE }}